### ISSUE TITLE
invoke SendMoreFrame occurred error while concurrent testing

### ISSUE THREAD

**Issue by liuyl1992** [zeromq/netmq#1005]
### Environment

    NetMQ Version:    4.0.1.8
    Operating System: win10
    .NET Version:     .NET6

### Expected behaviour
An error occurred while executing concurrent testing.
invoke  this is  _publisherSocket.SendMoreFrame("A:b") 
                   .SendFrame(DateTimeOffset.Now.ToString());

 An unhandled exception has occurred while executing the request：
System.IndexOutOfRangeException: Index was outside the bounds of the array.

fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.IndexOutOfRangeException: Index was outside the bounds of the array.
         at NetMQ.Core.Utils.YQueue`1.Push(T& val)
         at NetMQ.Core.YPipe`1.Write(T& value, Boolean incomplete)
         at NetMQ.Core.Pipe.Write(Msg& msg)
         at NetMQ.Core.Patterns.Utils.Distribution.Write(Pipe pipe, Msg& msg)
         at NetMQ.Core.Patterns.Utils.Distribution.Distribute(Msg& msg)
         at NetMQ.Core.Patterns.Utils.Distribution.SendToMatching(Msg& msg)
         at NetMQ.Core.Patterns.XPub.XSend(Msg& msg)
         at NetMQ.Core.SocketBase.TrySend(Msg& msg, TimeSpan timeout, Boolean more)
         at NetMQ.NetMQSocket.TrySend(Msg& msg, TimeSpan timeout, Boolean more)
         at NetMQ.OutgoingSocketExtensions.Send(IOutgoingSocket socket, Msg& msg, Boolean more)
         at NetMQ.OutgoingSocketExtensions.SendFrame(IOutgoingSocket socket, String message, Boolean more)
         at NetMQ.OutgoingSocketExtensions.SendMoreFrame(IOutgoingSocket socket, String message)
         at XXX.Plugin.Tdengine.ZeroMQController.PublisherSocket() in ZeroMQ\Controller\ZeroMQController.cs:line 55

### Actual behaviour
![image](https://user-images.githubusercontent.com/16396828/155146394-d044d097-c51b-4a5a-aa85-406245222840.png)
![image](https://user-images.githubusercontent.com/16396828/155147003-cd13488d-564b-4afe-81d9-878805f42828.png)

![image](https://user-images.githubusercontent.com/16396828/155147067-dd85e51e-c0e3-4eec-affe-ceb62a841bf9.png)

![image](https://user-images.githubusercontent.com/16396828/155147489-14316e9a-58e9-4bb0-9e25-904ea1139095.png)

project code github address：https://github.com/LeonKou/NetPro/blob/dev_6.0/src/sample/XXX.Plugin.ZeroMQ/Controller/ZeroMQController.cs

**Comment by liuyl1992** [comment]
Runs well without concurrent testing

**Comment by oocpawel** [comment]
are you using socket from multiple threads? I can see that you have registered it as a singleton
