### ISSUE TITLE
Closing and reopening connections

### ISSUE THREAD

**Issue by Phille88** [zeromq/netmq#176]
Hi,

For a project I'm working on, I was testing the case of closing en reopening connections:
```csharp
/// <summary>
/// A test to see whether the connections are properly closed, so the client can be reused.
/// </summary>
[TestMethod]
public void TestNetMQMessageSenderReuse()
{
    for (var i = 0; i < 10; i++)
    {
    using (var client = (NetMQSender<DummyMessage>) _messageBus.CreateSender<DummyMessage>(_endpoint))
    {
        client.Send(new DummyMessage("This is a dummy message"));
        Log.Info(this, "The message is sent.");
        Console.WriteLine("The message is sent.");
        client.Close(); //Shouldn't be called explicitly, 'cause being called by Dispose().  
        }
    }
}
```
```csharp
When i run this test, I get a Websocket exception like this one:
System.Net.Sockets.SocketException (0x80004005): An invalid argument was supplied
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at NetMQ.zmq.PgmSender.Init(PgmAddress pgmAddress)
   at NetMQ.zmq.SessionBase.StartConnecting(Boolean wait)
   at NetMQ.zmq.SessionBase.ProcessPlug()
   at NetMQ.zmq.ZObject.ProcessCommand(Command cmd)
   at NetMQ.zmq.IOThread.InEvent()
   at NetMQ.zmq.Poller.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at NetMQ.zmq.PgmSender.Init(PgmAddress pgmAddress)
   at NetMQ.zmq.SessionBase.StartConnecting(Boolean wait)
   at NetMQ.zmq.SessionBase.ProcessPlug()
   at NetMQ.zmq.ZObject.ProcessCommand(Command cmd)
   at NetMQ.zmq.IOThread.InEvent()
   at NetMQ.zmq.Poller.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

However, when I attach with a debugger, the test is executed slower, and i don't get any exception. Am i using this incorrectly. It is quite important for my project to let this test succeed.

Thanks in advance!

Kind regards,
Philippe

**Comment by xingyu3604** [comment]
I have meet the same question. 
    int rate = 100 * 1024;
    ret = zmq_setsockopt(publisher, ZMQ_RATE, &rate, sizeof(rate));
    assert(ret == 0);
send 10M/s data 
but the receive the message 1M/s
