### ISSUE TITLE
ThreadPoolSize issue raised from AsyncIO

### ISSUE THREAD

**Issue by ghost** [zeromq/netmq#219]
Hi guys,
Whenever I set the threadpoolsize to a couple of threads I am getting a Win32Exception from the CompletionPort at the AssociateSocket Method. 

The StackTrace is the following:
   at AsyncIO.Windows.CompletionPort.AssociateSocket(AsyncSocket socket, Object state) in c:\Users\geopars\Desktop\Code\github.async\trunk\Source\AsyncIO\Windows\CompletionPort.cs:line 78
   at NetMQ.zmq.Utils.Proactor.AddSocket(AsyncSocket socket, IProcatorEvents procatorEvents) in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\Utils\Proactor.cs:line 85
   at NetMQ.zmq.IOObject.AddSocket(AsyncSocket socket) in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\IOObject.cs:line 73
   at NetMQ.zmq.Transports.StreamEngine.Plug(IOThread ioThread, SessionBase session) in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\Transports\StreamEngine.cs:line 209
   at NetMQ.zmq.SessionBase.ProcessAttach(IEngine engine) in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\SessionBase.cs:line 396
   at NetMQ.zmq.ZObject.ProcessCommand(Command cmd) in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\ZObject.cs:line 82
   at NetMQ.zmq.IOThread.Ready() in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\IOThread.cs:line 90
   at NetMQ.zmq.IOThreadMailbox.RaiseEvent() in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\Mailbox.cs:line 114
   at NetMQ.zmq.Utils.Proactor.Loop() in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\Utils\Proactor.cs:line 115
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by somdoron** [comment]
Can you provide code so I can try to reproduce?

**Comment by geopars** [comment]
Yes of course. Let me put some code together.

**Comment by geopars** [comment]
Ok, here is a rough  a rough idea of what we are doing.
Client (Request Socket) <---> Server (Queue Device) 
Server (Queue Device) 
       <--> Worker_1 (ResponseSocket)					           
        ....
       <--> Worker_N (ResponseSocket)

I put together a little messy example in order to show it in more detail.


    public class ResponseSocketWrapper
    {
        private readonly ResponseSocket _socket;

        public ResponseSocketWrapper(NetMQContext context)
        {
            _socket = context.CreateResponseSocket();
            _socket.Options.Identity = Guid.NewGuid().ToByteArray();
            _socket.ReceiveReady += SocketOnReceiveReady;
        }

        private void SocketOnReceiveReady(object sender, NetMQSocketEventArgs e)
        {
            var msg = e.Socket.ReceiveMessages().Reconstruct();
        }

        public void Send(List<byte[]> message)
        {
            // ....
            // Raise event MessageReceived
        }

        public event EventHandler<byte[]> MessageReceived;

        private string Link;

        public void Connect(string link)
        {
            Link = link;
            _socket.Connect(Link);
        }

        public void Poll(TimeSpan timespan)
        {
            _socket.Poll(timespan);
        }

        public void Dispose()
        {
            _socket.Disconnect(Link);
            _socket.Dispose();
        }
    }

    public class RemoteWorker 
    {
        public string ID   { get; private set; }
        public bool   Flag { get; private set; }

        public IQFormatter _formatter;

        private readonly ResponseSocketWrapper _socket;


        public RemoteWorker(NetMQContext context, IQFormatter formatter)
        {
            ID = Guid.NewGuid().ToString();
            Exited  = false;
            Flag    = true;
            _formatter = formatter;
            _socket = new ResponseSocketWrapper(context);
            _socket.MessageReceived += SocketOnMessageReceived;
        }

        private void SocketOnMessageReceived(object sender, byte[] bytes)
        {
            var message = _formatter.DeSerialize(bytes);

           // Generate reply

            _socket.Send(reply);
        }

        public void Service()
        {
            while (Flag)
            {
                _socket.Poll(TimeSpan.FromMilliseconds(100));
            }
        }

        public void Connect(string link)
        {
            _socket.Connect(link);
        }

        public void Dispose()
        {
            Flag = false;
            _socket.MessageReceived -= SocketOnMessageReceived;
            _socket.Dispose();
        }
    }

    public class Server
    {
        private readonly QueueDevice _queue;
        private readonly Dictionary<string, RemoteWorker> _workers;
        private readonly List<Thread> _threads; 

        public Server(NetMQContext context, string frontend, string backend, int workers, IQFormatter formatter)
        {
            _workers = new Dictionary<string, RemoteWorker>();
            _queue   = new QueueDevice(context, frontend, backend);
            _threads = new List<Thread>();
            for (var i = 0; i < workers; i++)
            {
                var worker = new RemoteWorker(context, formatter);
                worker.Connect(backend);

                _workers.Add(worker.ID, worker);

                var thread = new Thread(_workers[worker.ID].Service);
                _threads.Add(thread);
                _threads[i].Start();
            }
            // Error when we start the QueueDevice 
            // The Exception is raied at the Proactor, AddSOcket method
            _queue.Start();
        }
    }

If we set the Threadpoolsize to 1 everything is fine. If I increase it to anything more than that I get the following exception.

The source of the Exception is the AsyncIO and the message is "The parameter is incorrect" 

at AsyncIO.Windows.CompletionPort.AssociateSocket(AsyncSocket socket, Object state)
   at NetMQ.zmq.Utils.Proactor.AddSocket(AsyncSocket socket, IProcatorEvents procatorEvents) in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\Utils\Proactor.cs:line 85
   at NetMQ.zmq.IOObject.AddSocket(AsyncSocket socket) in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\IOObject.cs:line 73
   at NetMQ.zmq.Transports.StreamEngine.Plug(IOThread ioThread, SessionBase session) in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\Transports\StreamEngine.cs:line 209
   at NetMQ.zmq.SessionBase.ProcessAttach(IEngine engine) in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\SessionBase.cs:line 396
   at NetMQ.zmq.ZObject.ProcessCommand(Command cmd) in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\ZObject.cs:line 82
   at NetMQ.zmq.IOThread.Ready() in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\IOThread.cs:line 90
   at NetMQ.zmq.IOThreadMailbox.RaiseEvent() in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\Mailbox.cs:line 114
   at NetMQ.zmq.Utils.Proactor.Loop() in c:\Users\geopars\Desktop\Code\github.netmq\trunk\src\NetMQ\zmq\Utils\Proactor.cs:line 115
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by somdoron** [comment]
Will test it, what transport are you using for front-end and back-end?

**Comment by geopars** [comment]
Are you referring to the type of transport socket?

**Comment by geopars** [comment]
Regarding the connection links they are standard tcp://*:port for the server and tcp://192.168.0.10:port for the client and workers

**Comment by somdoron** [comment]
Can it be that the context get disposed? the queue start method is
unblocking, so if after creating the server you exit the scope of the
context it will get disposed which can explain the issue.

I tried to reproduce the issue without success (I used netmq master and not
nuget).

**Comment by geopars** [comment]
Thanks Doron, I will have a look at it now and I will let you know how it does.

**Comment by geopars** [comment]
I checked the code according to your recommendation but the context wasn't getting disposed.
For the moment the code works fine when I am testing it with the nuget netmq (3.3.0.11). The above error shows only when I am running the server it with the latest netmq code (primarily because of the LOH fix). 

The server is part of an RPC solution I put together for our needs. I am preparing the code and I will push it as an independent project here on github. In the case something breaks it will be easier to track it down.

**Comment by somdoron** [comment]
Ok, once you have a repo let me know and I will try to fix that
