### ISSUE TITLE
NetMQ.FaultException Causes Application to crash

### ISSUE THREAD

**Issue by fsaremifar** [zeromq/netmq#220]
Hi guys,
I'm getting this exception from no where , it's happening randomly , not all the time , but it happens anyway on each time server runs,I'm using exactly the same code like Multithreaded Service 
I'm using this code on receive part of worker Routine:
```
 rep.ReceiveReady += (sender, args) =>
                {  
 var message = args.Socket.ReceiveMessage(); 
          OnReceiveBuffer(message.Last.BufferSize); //this will  raise an event for buffer size...
}
```
,also  I have an additional Publisher socket ,which currently sends a heartbeat message every 30 secs, but this exception seems to happen on worker routine part ( this stack trace is the only clue I have ,as Visual studio is not breaking anywhere,just throwing this as unhandled exception.

 will appreciate any suggestions,
here is the output:

A first chance exception of type 'NetMQ.FaultException' occurred in NetMQ
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>ConsoleHost.vshost.exe</AppDomain><Exception><ExceptionType>NetMQ.FaultException, NetMQ, Version=3.3.0.12, Culture=neutral, PublicKeyToken=a6decef4ddc58b3a</ExceptionType><Message></Message><StackTrace>   at NetMQ.Msg.Close()
   at NetMQ.zmq.Transports.V2Encoder.MessageReady()
   at NetMQ.zmq.Transports.V2Encoder.Next()
   at NetMQ.zmq.Transports.EncoderBase.GetData(ByteArraySegment&amp;amp; data, Int32&amp;amp; size, Int32&amp;amp; offset)
   at NetMQ.zmq.Transports.EncoderBase.GetData(ByteArraySegment&amp;amp; data, Int32&amp;amp; size)
   at NetMQ.zmq.Transports.StreamEngine.BeginSending()
   at NetMQ.zmq.Transports.StreamEngine.Handle(Action action, SocketError socketError, Int32 bytesTransferred)
   at NetMQ.zmq.Transports.StreamEngine.FeedAction(Action action, SocketError socketError, Int32 bytesTransferred)
   at NetMQ.zmq.Transports.StreamEngine.ActivateOut()
   at NetMQ.zmq.SessionBase.ReadActivated(Pipe pipe)
   at NetMQ.zmq.Pipe.ProcessActivateRead()
   at NetMQ.zmq.ZObject.ProcessCommand(Command cmd)
   at NetMQ.zmq.IOThread.Ready()
   at NetMQ.zmq.IOThreadMailbox.RaiseEvent()
   at NetMQ.zmq.Utils.Proactor.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</StackTrace><ExceptionString>NetMQ.FaultException
   at NetMQ.Msg.Close()
   at NetMQ.zmq.Transports.V2Encoder.MessageReady()
   at NetMQ.zmq.Transports.V2Encoder.Next()
   at NetMQ.zmq.Transports.EncoderBase.GetData(ByteArraySegment&amp;amp; data, Int32&amp;amp; size, Int32&amp;amp; offset)
   at NetMQ.zmq.Transports.EncoderBase.GetData(ByteArraySegment&amp;amp; data, Int32&amp;amp; size)
   at NetMQ.zmq.Transports.StreamEngine.BeginSending()
   at NetMQ.zmq.Transports.StreamEngine.Handle(Action action, SocketError socketError, Int32 bytesTransferred)
   at NetMQ.zmq.Transports.StreamEngine.FeedAction(Action action, SocketError socketError, Int32 bytesTransferred)
   at NetMQ.zmq.Transports.StreamEngine.ActivateOut()
   at NetMQ.zmq.SessionBase.ReadActivated(Pipe pipe)
   at NetMQ.zmq.Pipe.ProcessActivateRead()
   at NetMQ.zmq.ZObject.ProcessCommand(Command cmd)
   at NetMQ.zmq.IOThread.Ready()
   at NetMQ.zmq.IOThreadMailbox.RaiseEvent()
   at NetMQ.zmq.Utils.Proactor.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()</ExceptionString></Exception></TraceRecord>

**Comment by somdoron** [comment]
What version are you using?

**Comment by somdoron** [comment]
Ok saw the version in the bug. I will check it soon.

**Comment by fsaremifar** [comment]
Hi Somdoron  ,
Thanks for reply and your great job here , 
I think there's a issue with ReceiveMessage() ,  If I use a code like the code in below ,It won't crash.
I've created a full RMI system around the NetMq ,which will manage different services , and already did some ready to use clients for it on PHP and Javascript  and C++ ,
So far everything works great ,except this exception that happens sometimes , I will share this RMI system as soon I get something to share , 
however I don't mind to use a code like this , 
```csharp
 var message = args.Socket.ReceiveString(out hasMore);
                        if (hasMore) message = args.Socket.ReceiveString();
                        if (message == null||message.IsNullOrWhiteSpace()) return;
```

**Comment by leverate-somech** [comment]
@fsaremifar from the exception the issue is on the sending actually. Can you make a simple project the reproduce the issue? even one in a while will help

**Comment by fsaremifar** [comment]
@leverate-somech  I'll try to  make a simple project to reproduce  the issue,however this exception is throwing randomly , I don't know when or how , but after a while using the system it happens anyway , but usually when the I have more requests at same time( My guess) ... as far as the NetMq part I have the same code as that sample in repository, after receive it will process the message and then send back the reply(if there's any ) to client. all messages are string ,

**Comment by fsaremifar** [comment]
I've made some changes last night  to NetMq code to send these exceptions to an exception handler ignoring these exceptions as these exceptions can't be handled directly when using NetMq and I think the result is loss of message which causes this exception ,at least it's not crashing 
 ,however I'll try to make that simple project

**Comment by ndextraze-pbp** [comment]
I don't know it this helps, but we're seeing a similar issue with previous version of netmq 3.3.0.11. Might help you figure out where the problem is.

[NetMQException: ]
    NetMQ.zmq.Msg.Close():97
    NetMQ.zmq.V1Encoder.MessageReady():0
    NetMQ.zmq.V1Encoder.Next():30
    NetMQ.zmq.EncoderBase.GetData(ByteArraySegment& data, Int32& size, Int32& offset):64
    NetMQ.zmq.StreamEngine.OutEvent():15
    NetMQ.zmq.StreamEngine.ActivateOut():17
    NetMQ.zmq.SessionBase.ReadActivated(Pipe pipe):18
    NetMQ.zmq.Pipe.ProcessActivateRead():33
    NetMQ.zmq.ZObject.ProcessCommand(Command cmd):78
    NetMQ.zmq.IOThread.InEvent():16
    NetMQ.zmq.Poller.Loop():291
    System.Threading.ThreadHelper.ThreadStart_Context(Object state):20
    System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx):112
    System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx):0
    System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state):43
    System.Threading.ThreadHelper.ThreadStart():8

**Comment by somdoron** [comment]
Nicolas can you describe the usage? Or try to provide a code?

**Comment by ndextraze-pbp** [comment]
Sorry can't provide the code, but I can describe the setup.

2 servers on the same network. One hosting web services using IIS, one hosting app services. The app that crashed is a app service that was using one context with two sockets (1 pull socket binded using tcp://*:port, 1 publisher socket binded using tcp://*:port). There is 2 subscribers to the publisher socket (a web service and another app service).

During the night we ran load tests on our services. The program crashed at 9:22 am (way after the load tests had finish). The app service was processing messages normally and crashed out of the blue. The reason of the crash is an unhandled exception in the iothread-2 (the unhandled exception I posted). I also see in the logs multiple occurrence of the same exception occurring while the load tests were running:

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException()
   at NetMQ.zmq.Dist.Distribute(Msg& msg, SendReceiveOptions flags)
   at NetMQ.zmq.Dist.SendToMatching(Msg& msg, SendReceiveOptions flags)
   at NetMQ.zmq.XPub.XSend(Msg& msg, SendReceiveOptions flags)
   at NetMQ.zmq.SocketBase.Send(Msg& msg, SendReceiveOptions flags)
   at NetMQ.NetMQSocket.Send(Msg& msg, SendReceiveOptions options)
   at NetMQ.OutgoingSocketExtensions.Send(IOutgoingSocket socket, Byte[] data, Int32 length, SendReceiveOptions options)
   at Pbp.Api.Shared.Messaging.NetMq.NetMqFrameSender.Send(IOutgoingSocket socket, String msg, Boolean hasMore) in d:\BuildAgent1\work\ac3f1995e67c645e\Pbp.Api.Shared.Messaging\NetMq\NetMqFrameSender.cs:line 16

Hope this helps.

**Comment by ndextraze-pbp** [comment]
Also here are a glimpse at our logs for the timing of the error/fatal exception. Also included any monitored event on the socket.

20150203 172151.625 [20] ERROR -- The last ArgumentOutOfRangeException occured here
20150203 172226.767 [12] DEBUG netmq-monitor.2-publisher - Accepted Address=tcp://0.0.0.0:6744
20150203 172245.905 [iothread-2] FATAL -- The Msg.Close NetMqException occured here

**Comment by somdoron** [comment]
@ndextraze-pbp  or @fsaremifar if you can try to reproduce the bugs with following version it will be great:

https://github.com/somdoron/netmq/tree/MsgCloseDebug

This not solve the issue, but add an exception at different places to trying to understand where it comes from.

**Comment by fsaremifar** [comment]
@somdoron  I'll try it by tomorrow , thanks.

**Comment by ndextraze-pbp** [comment]
Sorry realized that the other exception I posted here was because we didn't use our publisher socket safely between multiple threads. I will fix that first, then see if I still have that same issue. If so I will try the proposed code to investigate more.

**Comment by yurialfredo** [comment]
Hi, I'm learning NetMQ.

Here a simple code for duplicate the error ( dll version 4.0.0.0  ).

Publisher -->:

`using System;
using System.Threading;
using NetMQ;
using NetMQ.Sockets;
using System.Threading.Tasks;

namespace Publisher
{
    class Program
    {
        private static PublisherSocket pubSocket = new PublisherSocket();
        static void Main(string[] args)
        {            
            Console.WriteLine("Publisher socket binding...");
            pubSocket.Options.SendHighWatermark = 1000;
            pubSocket.Bind("tcp://10.200.218.51:81");

            Task.Factory.StartNew(
                () => crazy_process());

            Task.Factory.StartNew(
                () => crazy_process2());
             
            Task.Factory.StartNew(
                () => crazy_process());

            Task.Factory.StartNew(
                () => crazy_process2());

            Task.Factory.StartNew(
                () => crazy_process2());
            Console.ReadKey();
        }

        static void crazy_process()
        {
            Random rand = new Random(50);
            for (var i = 0; i < 500; i++)
            {
                var randomizedTopic = rand.NextDouble();
                if (randomizedTopic > 0.5)
                { 
                    byte[] msg = new byte[] { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 };
                    pubSocket.SendMoreFrame("").SendFrame(msg);
                }
                else
                {
                    byte[] msg = new byte[] { 11, 22, 33, 44, 55, 66, 77, 88, 99, 110 };
                    pubSocket.SendMoreFrame("").SendFrame(msg);
                }
                Thread.Sleep(100);
            }
        }

        static void crazy_process2()
        {            
            for (var i = 0; i < 500; i++)
            {
                byte[] msg = new byte[] { 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
                pubSocket.SendMoreFrame("").SendFrame(msg);                
                Thread.Sleep(100);
            }
        }
    }
}`


Subscripter --> 
`using System;
using System.Collections.Generic;
using System.Text;
using System.Threading.Tasks;
using NetMQ;
using NetMQ.Sockets;

namespace Subscriber
{
    class Program
    {
        public static IList<string> allowableCommandLineArgs = new[] { "TopicA", "TopicB", "All" };
        static void Main(string[] args)
        {  
            string topic = "";
            Task.Factory.StartNew(() => ReceivePublicationFromServer(""));
            Task.Factory.StartNew(() => ReceivePublicationFromServer(""));             
            Console.WriteLine("Subscriber started for Topic : {0}", topic);      
            Console.ReadKey();
        }

        public static void ReceivePublicationFromServer(string topic)
        {
            using (var subSocket = new SubscriberSocket())
            {
                subSocket.Options.ReceiveHighWatermark = 1000;
                subSocket.Connect("tcp://10.200.218.51:81");
                subSocket.Subscribe(topic);
                Console.WriteLine("Subscriber socket connecting...");
                while (true)
                {
                    byte[] messageReceived = subSocket.ReceiveFrameBytes();
                    Console.WriteLine($"topic = {topic} --> {PrintByteArray(messageReceived)}");
                }
            }
        }

        public static string PrintByteArray(byte[] bytes)
        {
            var sb = new StringBuilder("new byte[] { ");
            foreach (var b in bytes)
            {
                sb.Append(b + ", ");
            }
            sb.Append("}");
            return sb.ToString();
        }
    }
}
`
