### ISSUE TITLE
3.3.0.12-rc1 OverflowException

### ISSUE THREAD

**Issue by SemtexCharlie** [zeromq/netmq#225]
Got the following stacktrace from a process that errored using the Nuget sourced 3.3.0.12-rc1. 

```
System.OverflowException: Arithmetic operation resulted in an overflow.
   at NetMQ.GCBufferPool.Take(Int32 size)
   at NetMQ.Msg.InitPool(Int32 size)
   at NetMQ.zmq.Transports.V2Decoder.EightByteSizeReady()
   at NetMQ.zmq.Transports.DecoderBase.ProcessBuffer(ByteArraySegment data, Int32 size)
   at NetMQ.zmq.Transports.StreamEngine.ProcessInput()
   at NetMQ.zmq.Transports.StreamEngine.FeedAction(Action action, SocketError socketError, Int32 bytesTransferred)
   at NetMQ.zmq.Utils.Proactor.Loop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
I don't have a capture of the message that caused it, but I can say that it was the **only socket** in the context/executing process (regular PUB socket) and it was open/established well ahead of this exception - suggesting it was the SentMessage() call I think.

Here's the simple send loop, no polling etc... (qItem type is `NetMQMessage`)

```csharp
foreach (var qItem in OutboundQueue.GetConsumingEnumerable(HaltFlag.Token))
{
  try
  {
    // Log Debug sending msg text removed
    Socket.SendMessage(qItem);
    SentMessageCount++;
  }
  catch (Exception ex)
  {
    // Log Error statement removed
  }
}
```

Haven't been able to reproduce it yet but will keep trying with more more granular debug statements... 

Should I fall back to 3.3.0.11? Did it have the proactor too?

**Comment by SemtexCharlie** [comment]
Update:

- Does happen with latest github code
- Doesn't happen with 3.3.0.11

More about causing this to happen...

I can almost reliably cause this to happen by running many processes at the same time that use the library. I was spinning up about 15 or 16 instances of exe's that use the newer NetMQ. There's no pattern to which process dies, it seems random.

**Comment by ndextraze-pbp** [comment]
Trace the exception to V2Decoder.EightByteSizeReady function.
We get a long size from the buffer, but it's suppose to be an unsigned 64-bit integer.
Then we check that it's not bigger than int.MaxValue. Since it's an unsigned long, the value might also go into negative since we cast it to a unsigned long. 
I might be able to provide a fix for the function, but it would still result in a DecodingError from the decoder.

I think the buffer might be uninitialized. I'll look into it after fixing the cast issue.

**Comment by SemtexCharlie** [comment]
Awesome.

I'd be happy to rerun the above scenario (many processes) after the fix and confirm.

**Comment by ndextraze-pbp** [comment]
Fix done. 
To test it you'll have to use the code at https://github.com/ndextraze-pbp/netmq

**Comment by ndextraze-pbp** [comment]
Also please make sure that you don't use the socket in more than one thread at a time. It might explain data corruption.

**Comment by SemtexCharlie** [comment]
Thanks Ndextraze-pbp - I'll try testing this shortly.

**Comment by somdoron** [comment]
@SemtexCharlie can you explain more how reproduce the issue? I'm trying to understand we do we even get a negative message size, it seems the message is malformed.

**Comment by ndextraze-pbp** [comment]
That's why I assumed thread safety as a possible problem that could create this, but I might be wrong.

**Comment by somdoron** [comment]
I'm not sure because it is coming directly from the wire...

**Comment by ndextraze-pbp** [comment]
Yes we know that the data is coming from the wire. So somehow a subscriber socket is sending a wrongly formatted subscription message to the publisher socket (it's the only kind of message it should ever receive, right?). So either:
1) there is corruption on the subscriber side (ie. thread safety issue or other)
2) a non netmq socket is connecting to that port and sending bad data
3) a different version of netmq/zeromq/encoder is connecting to that port and sending bad data

@SemtexCharlie What can you tell us about what connects to this publisher socket? or is it just dying with nothing ever connecting? do you have a monitoring socket connected?

**Comment by drewnoakes** [comment]
@SemtexCharlie, if you can reproduce this reliably and easily then [`git bisect`](http://git-scm.com/docs/git-bisect) might be a useful tool to find the exact commit that introduced the bug.

**Comment by AlekseiOhotnik** [comment]
Just had this on small broker with PUB and SUB sockets, SUB is connected to trusted source and is internal and PUB is exposed to public on port 443.

NetMQ version 3.3.2.2

Description: The process was terminated due to an unhandled exception.
Exception Info: System.OverflowException
Stack:
   at NetMQ.GCBufferPool.Take(Int32)
   at NetMQ.Msg.InitPool(Int32)
   at NetMQ.Core.Transports.V2Decoder.EightByteSizeReady()
   at NetMQ.Core.Transports.V2Decoder.Next()
   at NetMQ.Core.Transports.DecoderBase.ProcessBuffer(NetMQ.Core.Transports.ByteArraySegment, Int32)
   at NetMQ.Core.Transports.StreamEngine.ProcessInput()
   at NetMQ.Core.Transports.StreamEngine.Handle(Action, System.Net.Sockets.SocketError, Int32)
   at NetMQ.Core.Transports.StreamEngine.FeedAction(Action, System.Net.Sockets.SocketError, Int32)
   at NetMQ.Core.Transports.StreamEngine.InCompleted(System.Net.Sockets.SocketError, Int32)
   at NetMQ.Core.IOObject.InCompleted(System.Net.Sockets.SocketError, Int32)
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by somdoron** [comment]
Try to upgrade to latest version.

**Comment by somdoron** [comment]
Sorry, just noticed you are using the latest.

Any chance you are sending very big message? Bigger then 2^31?

**Comment by somdoron** [comment]
Read the following:

http://stackoverflow.com/q/3944320/1966074

We currently check for maximum of int, we might need to change it to minus
56 (probably because this is what dot net object and and array size are
using) and might be different on 32 vs 64.
Anyway the message size is too high, try to reduce it. At this point netmq
cannot support this message size.

**Comment by AlekseiOhotnik** [comment]
Yes, setting the limit on message size was my first idea when I saw the code around the crash site and will do just that. I still wonder were this payload came from cause no such traffic was registered on monitoring tools of network.

**Comment by AlekseiOhotnik** [comment]
It looks like the same exception may be triggered by having size described in buffer 
by 0xFF for all 8 bytes (giving -1). Having a check for negative will at least protect from malformed messages. I'll double check that sockets get properly handled in threads as they are created on startup main thread and from there on exclusive to their own workers. I can't remember if they are connected on worker threads or main thread for the first time. I don't think threads are an issue as service was running for quite a while before going down with overflow in my case.

**Comment by somdoron** [comment]
Are any of the clients using a very old version of netmq? We got the endian
wrong then...

Can you make a pull request of the negative check?
