### ISSUE TITLE
Unhandled exception at NetMQ.Core.Utils.Proactor.Loop()

### ISSUE THREAD

**Issue by romanros** [zeromq/netmq#371]
Occasionally I experience this unhandled exception:

```
Exception Info: System.Net.Sockets.SocketException
Stack:
   at AsyncIO.Windows.Socket.SetSocketOption(System.Net.Sockets.SocketOptionLevel, System.Net.Sockets.SocketOptionName, Byte[])
   at AsyncIO.Windows.Socket.UpdateConnect()
   at AsyncIO.Windows.CompletionPort.HandleCompletionStatus(AsyncIO.CompletionStatus ByRef, IntPtr, IntPtr, Int32)
   at AsyncIO.Windows.CompletionPort.GetMultipleQueuedCompletionStatus(Int32, AsyncIO.CompletionStatus[], Int32 ByRef)
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

It's difficult to reproduce - it takes hours to reproduce when running a connect/disconnect test. I use push/pull sockets and the netmq is built from the latest sources. The exception happens at a background thread created within netmq library at NetMQ.Core.Utils.Proactor.Loop() line 106.

I see the method AsyncIO.Windows.CompletionPort.GetMultipleQueuedCompletionStatus() could throw exceptions like SocketException or Win32Exception. NetMQ.Core.Utils.Proactor.Loop() shall catch all these exceptions otherwise if any thrown, the application will be terminated due to unhandled exception at the internal netmq background thread.

I am not sure how to handle the possible exceptions here. Just catch and ignore or quit the Loop() - means exit the worker NetMQ.Core.Utils.Proactor thread?

**Comment by yeowgit** [comment]
Hi,
I have experienced this exception as well. Similar to your reported case, i get this after socket is being disconnected. Any help on how to solve this? 
thanks

**Comment by somdoron** [comment]
Do you have more information about the exception?

**Comment by nerzhulart** [comment]
Hi! I've faced with that exception when I'm running NetMQ on Mono under Windows. It's reproduced stable. The workaround is to call ForceDotNet.Force() (from AsyncIO) before using NetMQ.

**Comment by somdoron** [comment]
Can you attach your stacktrace?

**Comment by general-tycoon** [comment]
We just experienced a slightly different unhandled exception, also from Proactor.Loop()

We have a slew of Windows services, all using a common library that wraps NetMQ. They all started crashing for a period this afternoon, then, a hour or so later, this problem went away. We're still trying to understand if there was some kind of network event or what was occurring.

We're using the NetMQScheduler and Task Factory pattern as shown at http://somdoron.com/2013/06/netmq-scheduler/. 

```
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: NetMQ.NetMQException
Stack:
   at NetMQ.Core.Transports.Tcp.TcpConnector.OutCompleted(System.Net.Sockets.SocketError, Int32)
   at NetMQ.Core.IOObject.OutCompleted(System.Net.Sockets.SocketError, Int32)
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by somdoron** [comment]
Which versions are you using (NetMQ and AsyncIO), there was a fix to to
TCPConnector recently that might fix your issue:

https://github.com/zeromq/netmq/commit/05beccc53d50e1acded28592fbbea8c1d9041633

Try building NetMQ from master (or using latest pre-release version on
nuget) and using latest AsyncIO version.

**Comment by somdoron** [comment]
More info:

https://github.com/zeromq/netmq/pull/397

Also can you find out what was the SocketError in your case? It is probably
just a socket error which we are not handling yet.

**Comment by general-tycoon** [comment]
We are using NetMQ 3.3.2.1 and ASyncIO 0.1.17.0

It looks like I need to wrap my call to Poller.PollTillCancelled() with something to log the exception to find out the specifics of the NetMQException.

**Comment by awneesh123** [comment]
I am using NetMQ v4.0.30319 and ASyncIO 0.1.25.0
windows service giving below error in event viewer while stopping or restarting services:
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: NetMQ.NetMQException
Stack:
   at NetMQ.Core.Transports.Tcp.TcpConnector.OutCompleted(System.Net.Sockets.SocketError, Int32)
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by daliboraleksov** [comment]
I am almost always able to reproduce this issue

```
Unhandled Exception: System.Net.Sockets.SocketException: Invalid argument
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at NetMQ.Core.Transports.Tcp.TcpConnector.OutCompleted(SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

I'm running on
* macOS High Sierra
* dot net core 2.1.0
* NetMQ 4.0.0.1

Steps to reproduce:
* start zmq-client
* start zmq-server
* stop/start by doing the `CTRL+C` zmq-server/zmq-client in random order....just stop/start them until you get the error message from ^^^

Here is the sample code

**zmq-client**

```{C#}
static void Main(string[] args)
        {
            AsyncIO.ForceDotNet.Force();
            var pusher = new PushSocket();
            pusher.Connect("tcp://localhost:5555");
            var timeout = TimeSpan.FromSeconds(1);

            AppDomain.CurrentDomain.ProcessExit += (s, e) =>
            {
                pusher.Close();
            };

            var i = 0;
            while (true)
            {
                pusher.TrySendFrame(timeout, i.ToString());
                Console.WriteLine("Sent " + i.ToString());
                i++;
            }
        }
```

**zmq-server**

```{C#}
static void Main(string[] args)
        {
            AsyncIO.ForceDotNet.Force();
            var puller = new PullSocket();
            puller.Options.Linger = TimeSpan.FromSeconds(1);
            puller.Bind("tcp://localhost:5555");
            Console.WriteLine("Waiting on messages");

            AppDomain.CurrentDomain.ProcessExit += (s, e) =>
            {
                puller.Close();
            };

            while (true)
            {
                var message = puller.ReceiveFrameString();
                Console.WriteLine("Processing message " + message);
            }
        }
```

**Comment by clark0820** [comment]
@somdoron 

Do you happen to know any change from NETMQ 4.0.0.1 to 4.0.0.207 that may have mitigated socket exceptions that were thrown within "NetMQ.Core.Utils.Proactor.Loop()"?

Our team is currently having similar Socket Exception issue. We wonder if we can nail down the root cause so that we are confident the issue was fixed.

Many thanks in advance!
