### ISSUE TITLE
IndexOutOfRangeException in YQueue

### ISSUE THREAD

**Issue by general-tycoon** [zeromq/netmq#375]
Hi-

We're experiencing a `IndexOutOfRangeException` in `YQueue`. This is when we send a message through a Publish socket that is bound.

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at NetMQ.zmq.Utils.YQueue`1.Push(T& val)
   at NetMQ.zmq.Pipe.Write(Msg& msg)
   at NetMQ.zmq.Patterns.Utils.Distribution.Write(Pipe pipe, Msg& msg)
   at NetMQ.zmq.Patterns.Utils.Distribution.Distribute(Msg& msg, SendReceiveOptions flags)
   at NetMQ.zmq.Patterns.Utils.Distribution.SendToMatching(Msg& msg, SendReceiveOptions flags)
   at NetMQ.zmq.Patterns.XPub.XSend(Msg& msg, SendReceiveOptions flags)
   at NetMQ.zmq.SocketBase.Send(Msg& msg, SendReceiveOptions flags)
   at NetMQ.OutgoingSocketExtensions.Send(IOutgoingSocket socket, Byte[] data, Int32 length, SendReceiveOptions options)
   at NetMQ.OutgoingSocketExtensions.SendMessage(IOutgoingSocket socket, NetMQMessage message, Boolean dontWait)
```

We're using NetMQ 3.3.0.12-rc1

**Comment by somdoron** [comment]
Any chance you are using the socket from multiple threads?

**Comment by general-tycoon** [comment]
Yes, totally. `SendMessage` is called by multiple threads. Whoops - did I miss a fundamental aspect of usage? Is it as simple as throwing a `lock` around the `SendMessage` or do all calls have to come from the same thread?

**Comment by general-tycoon** [comment]
Ah, I see Socket is not thread safe. I will compensate. Thanks! I should have read closer.

**Comment by iiwaasnet** [comment]
Only NetMQContext is thread-safe. Socket should never be used in the other thread, than the one it are created in.

**Comment by drewnoakes** [comment]
@general-tycoon take a look at the scheduler class. You can use it to schedule operations (such as sends) in a threadsafe way.
