### ISSUE TITLE
CreatePublisherSocket at win xp

### ISSUE THREAD

**Issue by haoxiaokun** [zeromq/netmq#412]
Runing NETMQ
Win7 IS Succeed
Windows XP SP3 Is Faild

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.EntryPointNotFoundException
Stack:
at AsyncIO.Windows.UnsafeMethods.GetQueuedCompletionStatusEx(IntPtr, IntPtr, Int32, Int32 ByRef, Int32, Boolean)
at AsyncIO.Windows.CompletionPort.GetMultipleQueuedCompletionStatus(Int32, AsyncIO.CompletionStatus[], Int32 ByRef)
at NetMQ.Core.Utils.Proactor.Loop()
at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
at System.Threading.ThreadHelper.ThreadStart()

**Comment by somdoron** [comment]
At the first line of the program try to run this:
ForceDotNet.Force();

**Comment by haoxiaokun** [comment]
yes,it is good work,think you !
