### ISSUE TITLE
Unhandled exception in PgmSender.BeginSending

### ISSUE THREAD

**Issue by thomasdc** [zeromq/netmq#558]
Yesterday we experienced an unhandled exception in `PgmSender.BeginSending`. This was caused by an underlying `SocketException` (see below).

Is there a better way to handle these kind of problems more gracefully instead of throwing an exception in a thread created by the library? Can I configure it to recover automatically?

<pre>Type: NetMQ.NetMQException
Message: Exception of type 'NetMQ.NetMQException' was thrown.
Stack Trace: 
   at NetMQ.Core.Transports.Pgm.PgmSender.BeginSending()
   at NetMQ.Core.ZObject.ProcessCommand(Command cmd)
   at NetMQ.Core.IOThread.Ready()
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Caused by: 
Type: System.Net.Sockets.SocketException
Message: An established connection was aborted by the software in your host machine
Stack Trace: 
   at AsyncIO.Windows.Socket.Send(Byte[] buffer, Int32 offset, Int32 count, SocketFlags flags)
   at NetMQ.Core.Transports.Pgm.PgmSender.BeginSending()<pre>

**Comment by somdoron** [comment]
Which version are you using?

**Comment by thomasdc** [comment]
We're using version 3.3.2.2.

**Comment by somdoron** [comment]
It should be fixed with master or latest nuget version

**Comment by somdoron** [comment]
the fix was here:

https://github.com/zeromq/netmq/pull/500

**Comment by somdoron** [comment]
it was first reported in following issue:

https://github.com/zeromq/netmq/issues/481

**Comment by thomasdc** [comment]
Thanks, I'll have a try with the latest version.
