### ISSUE TITLE
Random crashes in NetMQPoller

### ISSUE THREAD

**Issue by Telavian** [zeromq/netmq#564]
I have a windows service that is running well however there seems to sometimes be crashes in the NetMQPoller run method.

```
Description: The process was terminated due to an unhandled exception.
Exception Info: NetMQ.FaultException
   at NetMQ.Msg.Close()
   at NetMQ.Core.Patterns.Utils.FairQueueing.RecvPipe(NetMQ.Core.Pipe[], NetMQ.Msg ByRef)
   at NetMQ.Core.Patterns.Dealer.ReceiveInternal(NetMQ.Msg ByRef)
   at NetMQ.Core.Patterns.Dealer.XHasIn()
   at NetMQ.Core.SocketBase.GetSocketOption(NetMQ.Core.ZmqSocketOption)
   at NetMQ.Core.Utils.Selector.Select(NetMQ.Core.Utils.SelectItem[], Int32, Int64)
   at NetMQ.NetMQPoller.Run()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()
```

What can I do to help solve this problem?

**Comment by somdoron** [comment]
any chance you are using the socket outside from the poller thread?

NetMQSocket is not thread safe, this kind of exception usually indicate you are using the socket outside of the poller thread.

Once you added a socket to a poller and the poller is running you can only use the socket from the poller thread (ReceiveReady event or other events raised by the poller, like NetMQTimer or NetMQQueue).

**Comment by Telavian** [comment]
I don't think so. My code wraps the NetMQ socket and all receives are in the ReceiveReady and all sends are through:
Task.Factory.StartNew(() => _socket.SendMultipartMessage(message.Message), CancellationToken.None, TaskCreationOptions.None, _poller);

**Comment by somdoron** [comment]
Ok, any chance you are closing the socket from another thread? maybe before removing it from the poller?

**Comment by somdoron** [comment]
Also how often does it happen?

**Comment by Telavian** [comment]
It doesn't happen very often however it does seem to crash the entire application when it does.

The update code was not being run on the poller thread. I can try that and see if I notice the issue.

**Comment by somdoron** [comment]
Does the update code close the socket?

**Comment by Telavian** [comment]
The code does call dispose on the old invalid socket.

**Comment by somdoron** [comment]
@Telavian did you manage to fix the issue? do you need more help?

**Comment by Telavian** [comment]
I believe it is fixed or at least I don't see the error anymore.
All poller actions need to take place on the poller thread. Makes some sense but can be a bit confusing if not designed correctly.
