### ISSUE TITLE
Basic Router failing on ubuntu 14.04 dotnet core

### ISSUE THREAD

**Issue by chris-ray** [zeromq/netmq#586]
### Environment

    NetMQ Version:    4.0.0.4-rc4
    Operating System: Ubuntu 14.04
    .NET Version:     um... core... v1 i think... still don't understand all the new naming crap

### Expected behaviour

not to crash on start

### Actual behaviour

Unhandled Exception: NetMQ.NetMQException: Exception of type 'NetMQ.NetMQException' was thrown. ---> System.Net.Sockets.SocketException: Operation not supported
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at NetMQ.Core.Transports.Tcp.TcpListener.SetAddress(String addr)
   --- End of inner exception stack trace ---
   at NetMQ.Core.Transports.Tcp.TcpListener.SetAddress(String addr)
   at NetMQ.Core.SocketBase.Bind(String addr)
   at NetMQ.NetMQSocket..ctor(ZmqSocketType socketType, String connectionString, DefaultAction defaultAction)
   at netmqcoretest.Program.Main(String[] args)

### Steps to reproduce the behaviour

```
namespace netmqcoretest
{
    using NetMQ;
    using NetMQ.Sockets;
    using System;

    public class Program
    {
        public static void Main(string[] args)
        {
            var uri = $"@tcp://*:6000";
            using (var router = new RouterSocket(uri))
            {
                Console.WriteLine($"server started: {uri}");

                while (true)
                {
                    var identity = router.ReceiveFrameBytes();
                    var value = router.ReceiveFrameString();
                    router.SendMoreFrame(identity);
                    router.SendFrame(value);
                }
            }
        }
    }
}

```

**Comment by somdoron** [comment]
Fixed with latest release:

https://www.nuget.org/packages/NetMQ/4.0.0-rc5

**Comment by chris-ray** [comment]
works! thanks.
