### ISSUE TITLE
the proxy throw a exception

### ISSUE THREAD

**Issue by GuojieLin** [zeromq/netmq#611]
### Environment

```
NetMQ Version:    3.3.3.4
Operating System: win10
.NET Version:     4
```
### Expected behaviour

implement async server by proxy
### Actual behaviour

```
In Stream.XSend
   at NetMQ.Core.Patterns.Stream.XSend(Msg& msg)
   at NetMQ.Core.SocketBase.TrySend(Msg& msg, TimeSpan timeout, Boolean more)
   at NetMQ.Proxy.ProxyBetween(IReceivingSocket from, IOutgoingSocket to, IOutgoingSocket control)
   at NetMQ.NetMQSocket.InvokeEvents(Object sender, PollEvents events)
   at NetMQ.NetMQPoller.Run()
   at Freelance.ModelOne.Server.Program.ForwardProxy(String orignalAddress, String targetAddress)
```
### Steps to reproduce the behaviour

```
            using (receivedSocket)
            {
                using (backend = new DealerSocket("@" + targetAddress))
                {
                    while (true)
                    {
                        Proxy proxy = new Proxy(receivedSocket, backend);
                        manualResetEvent.Set();
                        proxy.Start();
                    }
                }
            }
```

when the application start,it works well, after a few minutes.,it will throw a exception. what's going on ?

**Comment by GuojieLin** [comment]
when the client socket close,the proxy reply client will throw new exception,and then ,it can receive message and forward to backend,it also can reply client success without exception,but client can't receive message anymore, i use command 'netsate' in cmd,and the connetion is ESTABLISHED, then i Imitation  the proxy implement the poll forward message,
init and start poll
```
poller = new NetMQPoller();
            poller.Add(receivedSocket);
            poller.Add(backend);
            receivedSocket.ReceiveReady += OnFrontendReady;
            backend.ReceiveReady += OnBackendReady;
poll.Run();
```
on frontend ready and on backend ready
```
        private static void OnBackendReady(object sender, NetMQSocketEventArgs e)
        {
            ForwardBetween(backend, receivedSocket);
        }
        private static void OnFrontendReady(object sender, NetMQSocketEventArgs e)
        {
            ForwardBetween(receivedSocket, backend);
        }
```
proxybetween
```
 private static void ForwardBetween(IReceivingSocket from, IOutgoingSocket to)
        {
            Msg msg1 = new Msg(), msg2 = new Msg();
            try
            {
                msg1.InitEmpty();
                msg2.InitEmpty();
                bool hasMore;
                do
                {
                    from.Receive(ref msg1);
                    hasMore = msg1.HasMore;
                    to.Send(ref msg1, hasMore);//throw a exception 
                } while (hasMore);
            }
            catch (Exception exception)
            {
                Logger.WriteError(exception);
            }
            finally
            {
                msg2.Close();
                msg1.Close();
            }
```

and i debugging the app,First ,i try to normal received and success,and it works. Then, when i received message, i  wait the connection break. then i continue send to client , and it throw a exception. after the above operate, i send the message to server again, the server works well,it can received and also send to client without any exception. but the client just can't received the message anymore.

**Comment by GuojieLin** [comment]
i try again, i change the code.
```

            List<byte[]> msg1 = null;
            try
            {
                if (from.TryReceiveMultipartBytes(TimeSpan.FromMilliseconds(receivedoutime), ref msg1))
                {
                    if (!to.TrySendMultipartBytes(TimeSpan.FromMilliseconds(sendouttime), msg1))
                    {
                              //logging
                    }
                }
                else
                {
                              //logging
                }
            }
            catch (Exception exception)
            {
                              //logging
            }
```

and it works . i think it is not carry exception in proxy ,do you think so ? When send failed, it throw a exception ,and the poll will be crash.

**Comment by somdoron** [comment]
what exception is thrown? 
Any chance you are using any of the sockets from other threads?
