### ISSUE TITLE
Not suport on Linux

### ISSUE THREAD

**Issue by lianghugg** [zeromq/netmq#659]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: centos7
    .NET Version:     .netcore1.1

### Expected behaviour
exception:Opertaion is not suport on linux platform
at AsyncIO.DotNet.NativeSocket.IOControl()

**Comment by simonbaas** [comment]
I'm also running into problems when running on Ubuntu (16.04) using .NET Core 1.0.4, NetMQ 4.0.0.1 and AsyncIO 0.1.26. The problem seems to be BindRandomPort and I'm getting the following error shown below when the method is called. When running the same code on Windows 10 it works.

```
Unhandled Exception: System.PlatformNotSupportedException: Operation is not supported on this platform.
   at System.Net.Sockets.SocketPal.WindowsIoctl(SafeCloseSocket handle, Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue, Int32& optionLength)
   at System.Net.Sockets.Socket.IOControl(Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at AsyncIO.DotNet.NativeSocket.IOControl(IOControlCode ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at NetMQ.Core.Transports.Tcp.TcpConnector.OutCompleted(SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by MercedeX** [comment]
It has been a long time, does it run on linux now?

**Comment by somdoron** [comment]
I'm using NetMQ on linux everyday
