### ISSUE TITLE
Unity & WSA (UWP): Failed to run serialization weaver

### ISSUE THREAD

**Issue by basingh89** [zeromq/netmq#678]
### Environment

NetMQ Version: master (also tried v4.0.0.1)
Operating System: Windows 10
.NET Version: .NET4.6, UWP10
Unity 2017 (beta)

### Steps to reproduce the behavior

1. I cloned the repo and built it using VS2017. 
2. I'm using .NET4.6 with Unity 2017 beta, so I copied the AsyncIO and NetMQ DLLs  from the `net40` folder to be used in the standalone and Unity Editor. I also copied the two DLLs from `uap10.0` folder to be used for the WSA builds.
3. I tested Push/Pull sockets from the Unity Editor, and everything works once I add `AsyncIO.ForceDotNet.Force()`.
4. However, when I try to build the WSA/UWP project, Unity throws this exception:

`UnityException: Failed to run serialization weaver with command "Temp\StagingArea\Data\Managed\NetMQ.dll" "-pdb" "-verbose" "-unity-engine=Temp\StagingArea\Data\Managed\UnityEngine.dll"`

### Additional details

I did some searching and found this on Unity forums: https://forum.unity3d.com/threads/windows-8-phone-failed-to-run-serialization-weaver.236660/#post-1752460. So it seems that Unity adds some code to speed up serialization for classes marked with `[Serializable]`. However, I only found one class with that attribute: `NetMQException`. But even there, it seems that the attribute is disabled for NETSTANDARD1_3 and UAP. So, I'm confused why this is happening.

Normally, I would think this a bug in Unity. However, I have other DLLs that work fine (followed the same steps)...namely, Newtonsoft.Json.

**Comment by basingh89** [comment]
Digging down further, I also see this error:

```
Mono.Cecil.ResolutionException: Failed to resolve System.Net.Sockets.SocketOptionName
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self)
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant)
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type)
   at Mono.Cecil.MetadataBuilder.AddField(FieldDefinition field)
   at Mono.Cecil.MetadataBuilder.AddFields(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type)
   at Mono.Cecil.MetadataBuilder.AddTypeDefs()
   at Mono.Cecil.MetadataBuilder.BuildTypes()
   at Mono.Cecil.MetadataBuilder.BuildModule()
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__1_0(MetadataBuilder builder, MetadataReader _)
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read)
   at Mono.Cecil.ModuleWriter.WriteModuleTo(ModuleDefinition module, Stream stream, WriterParameters parameters)
   at Mono.Cecil.ModuleDefinition.Write(String fileName, WriterParameters parameters)
   at usw.Weaver.WeaveAssembly(String assemblyPath, AssemblyDefinition unityEngineAssemblyDefinition, ReaderParameters readerParameters) in C:\buildslave\unity\build\Tools\SerializationWeaver\sw\Weaver.cs:line 107
   at usw.Weaver.Weave() in C:\buildslave\unity\build\Tools\SerializationWeaver\sw\Weaver.cs:line 50
   at usw.Program.RunProgram(ConversionOptions options) in C:\buildslave\unity\build\Tools\SerializationWeaver\sw\Program.cs:line 33
   at usw.Program.Main(String[] args) in C:\buildslave\unity\build\Tools\SerializationWeaver\sw\Program.cs:line 14
```

**Comment by JonBoyleCoding** [comment]
I can (unfortunately) confirm I have the same issue. I don't believe I can provide any more information than has been already provided though.

**Comment by JonBoyleCoding** [comment]
Looking slightly more in-depth, it appears that a lot of the Socket stuff used in PgmSocket.cs, TcpConnector.cs, TcpListener.cs, Signalar.cs, and NetMQBeacon is problematic in the UAP build that has been done on my machine.

**Comment by JonBoyleCoding** [comment]
I just deployed the app I was making without processing the files, and the program ran until it couldn't find 'System.Net.Sockets'.

**Comment by basingh89** [comment]
I tried making my own enumeration for System.Net.Sockets.SocketOptionName, and compiled with NetMQ.  But it that didn't work either. Compatibility issues with AsyncIO.
