### ISSUE TITLE
My winform app has an error caused by NETMQ at approximately every interval

### ISSUE THREAD

**Issue by flzxsqcysyhljt** [zeromq/netmq#732]
### Environment

    NetMQ Version: 4   
    Operating System:win7 sp1  32
    .NET Version:4.0     
    

### Steps to reproduce the behaviour
I don't know how to Steps to reproduce.
This problem does not occur in Development environment. 
My Development environment : win7 sp1 64

MQ mode : request/reply
My connectionString : @inproc://tsp-xxxxx

I'm freaking out.

### Error Message
Thread ID:[reaper-1] 
 Error:
System.Net.Sockets.SocketException (0x80004005): An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.Socket.Receive(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags)
   at NetMQ.Core.Mailbox.TryRecv(Int32 timeout, Command& command)
   at NetMQ.Core.Reaper.InEvent()
   at NetMQ.Core.Utils.Poller.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.runTryCode(Object userData)
   at System.Runtime.CompilerServices.RuntimeHelpers.ExecuteCodeWithGuaranteedCleanup(TryCode code, CleanupCode backoutCode, Object userData)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean ignoreSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by flzxsqcysyhljt** [comment]
Upgrade [. Netframework] version to 4.5 or above.

It solves the problem, but doesn't know why.
