### ISSUE TITLE
Poller thread of XPublisherSocket and XSubscriberSocket crashes after number of topics exceed HighWaterMark

### ISSUE THREAD

**Issue by snowdaq** [zeromq/netmq#734]
### Environment

    NetMQ Version: problem exists in most recent versions of v3, v4 and current code in master   
    Operating System: Win 7, Win 10, Win Server 2012, Win Server 2016
    .NET Version: .NET 4.5, .NET Core    

### Expected behaviour
Number of unique topics subscribed in a PubX\SubX scenario can exceed high water marks without causing the application to crash.

### Actual behaviour
Application crashes with ArgumentOutOfRangeException - not as soon as the number of topics has been reached, but at the next "hiccup" of a publisher.

### Exception and stack trace

```
Unhandled Exception: System.ArgumentOutOfRangeException: Index was out of range.
 Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argu
ment, ExceptionResource resource)
   at NetMQ.Core.Patterns.Utils.ArrayExtensions.Swap[T](List`1 items, Int32 inde
x1, Int32 index2)
   at NetMQ.Core.Patterns.Utils.Distribution.Activated(Pipe pipe)
   at NetMQ.Core.ZObject.ProcessCommand(Command cmd)
   at NetMQ.Core.SocketBase.ProcessCommands(Int32 timeout, Boolean throttle)
   at NetMQ.Core.SocketBase.GetSocketOption(ZmqSocketOption option)
   at NetMQ.NetMQSelector.Select(Item[] items, Int32 itemsCount, Int64 timeout)
   at NetMQ.NetMQPoller.Run()
   at NetMqCrashReproduction.Program.RunXPubXSub() 
   at NetMqCrashReproduction.Program.LaunchComponent(String[] args) 
   at NetMqCrashReproduction.Program.Main(String[] args) 
```

### Cause of the exception in the codebase

If at any point XPub\XSub endpoints lose connection to a Publisher while having more subscriptions than the HWM, then the poller thread will crash when the Publisher reconnects. 

The following is what we think is happening 

When the connection is dropped all the subscriptions are written onto the new pipe, with those above the HWM being discarded. This happens in the callback function s_sendSubscription of /Core/Patterns/XSub.cs 

When the connection is re-established, the pipe will start draining, triggering Distribution.Actived (/Core/Patterns/Utils/Distribution.cs) to call m_pipes.Swap with an index that is out of range because the pipe was allowed to hit the HWM without the Distribution being made aware of it, so the Distribution still counts it as an eligible pipe. Distribution seems to use ints m_eligible and m_active to keep track of things, but what happens in s_sendSubscription does not affect these counters.

### Related Issues

This bug is also the cause of the unresolved issue here: https://github.com/zeromq/netmq/issues/581. It may also be related to the problem described here: https://groups.google.com/forum/#!topic/netmq-dev/2aditkZI0QI.

### Steps to reproduce the behaviour

Running the following code as a console application will launch 4 instances of itself with command line arguments that will cause each instance to act as a particular part of reproducing this scenario: two subscribers, one "relay" with the XPublisherSocket and XSubscriberSocket and one publisher. The code will launch them in the right order so that you can just run it and you will see the crash. Output from the child processes are redirected to the main window and shown in the console as green.

```csharp

namespace NetMqCrashReproduction
{
    class Program
    {
        /* change these ports if you're already using them for something else */
        const int XSubPort = 6098;
        const int XPubPort = 6099;

        static void Main(string[] args)
        {

            if (args.Length == 0)
            {
                LaunchProcess("SUBSCRIBER1");
                LaunchProcess("SUBSCRIBER2");
                LaunchProcess("XPUBXSUB");
                LaunchProcess("PUBLISHER");
            }
            else
            {
                LaunchComponent(args);
            }
            System.Console.Read();
        }

        static void RunSubscriber(string TopicPrefix)
        {
            var SubscriberSocket = new NetMQ.Sockets.SubscriberSocket();
            SubscriberSocket.Connect("tcp://127.0.0.1:" + XPubPort);

            var Poller = new NetMQ.NetMQPoller();
            Poller.Add(SubscriberSocket);

            for (int i = 1; i < 600; i++)
            {
                SubscriberSocket.Subscribe(TopicPrefix + i);
            }
            
            Poller.RunAsync();

        }

        static void RunXPubXSub()
        {
            
            var XPubSocket = new NetMQ.Sockets.XPublisherSocket();
            XPubSocket.Bind("tcp://*:" + XPubPort);

            var XSubSocket = new NetMQ.Sockets.XSubscriberSocket();
            XSubSocket.Bind("tcp://*:" + XSubPort);

            var Proxy = new NetMQ.Proxy(XSubSocket, XPubSocket);
            Proxy.Start();
        }

        static void RunPublisher()
        {

            var PublisherSocket = new NetMQ.Sockets.PublisherSocket();

            var Poller = new NetMQ.NetMQPoller();

            Poller.Add(PublisherSocket);

            PublisherSocket.Connect("tcp://127.0.0.1:" + XSubPort);

            Poller.RunAsync();

        }
        
        static void LaunchProcess(string Argument)
        {
            
            var Process = new System.Diagnostics.Process();
            Process.StartInfo.FileName = System.AppDomain.CurrentDomain.FriendlyName;
            Process.StartInfo.Arguments = Argument;
            Process.StartInfo.UseShellExecute = false;
            Process.StartInfo.RedirectStandardOutput = true;
            Process.StartInfo.RedirectStandardError = true;
            Process.OutputDataReceived += (sender, e) =>
            {
                System.ConsoleColor oldColor = System.Console.ForegroundColor;
                System.Console.ForegroundColor = System.ConsoleColor.Green;
                System.Console.WriteLine(Argument + " - " + e.Data);
                System.Console.ForegroundColor = oldColor;
            };
            Process.ErrorDataReceived += (sender, e) =>
            {
                System.ConsoleColor oldColor = System.Console.ForegroundColor;
                System.Console.ForegroundColor = System.ConsoleColor.Green;
                System.Console.WriteLine(Argument + " - " + e.Data);
                System.Console.ForegroundColor = oldColor;
            };
            Process.Start();
            Process.BeginOutputReadLine();
            Process.BeginErrorReadLine();
            System.Console.WriteLine("Process for component {0} launched, waiting 10 seconds...", Argument);
            System.Threading.Thread.Sleep(10000);
        }

        

        static void LaunchComponent(string[] args)
        {

            switch (args[0])
            {
                case "SUBSCRIBER1":
                    System.Console.WriteLine("Subscribing to 600 unique topics");
                    RunSubscriber("one");
                    break;
                case "SUBSCRIBER2":
                    System.Console.WriteLine("Subscribing to 600 more unique topics");
                    RunSubscriber("two");
                    break;
                case "XPUBXSUB":
                    System.Console.WriteLine("Binding XPub\\XSub sockets");
                    RunXPubXSub();
                    break;
                case "PUBLISHER":
                    System.Console.WriteLine("Connecting publisher");
                    RunPublisher();
                    break;
            }            
        }

    }
}

```

**Comment by sabrogden** [comment]
Any updates on this issue?  We are seeing this same exception stack trace.  Using NetMQ 4.0.0.1.
