### ISSUE TITLE
Poller(Reaper) timeout cannot be set

### ISSUE THREAD

**Issue by tnavda** [zeromq/netmq#740]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: Windows 10
    .NET Version:     4.7.1

### Expected behaviour
Stopping SubscriberSocket gracefully

### Actual behaviour
It appears you can't set a timeout for the underlying Poller of a subscriberSocket

From Poller.cs
`SocketUtility.Select(readList, /*writeList*/null, errorList, timeout != 0 ? timeout * 1000 : -1);`

timeout is set by `int timeout = ExecuteTimers();`

ExecuteTimers() => How can you add a timer to return a value to stop it from always blocking?

**Comment by tnavda** [comment]
Actually this looks like the Reaper's poller for that Socket, but since its always blocking, you can't tell it you are shutting down

**Comment by tnavda** [comment]
Doing some more inspection, it looks like you will always generate an exception in a Poller when you issue a stop command.  Once you come around from a TryRecv loop, if you've issued a command to Stop it.  Maybe its just acceptable to have these?

"Exception thrown: 'NetMQ.TerminatingException' in NetMQ.dll
Exception thrown: 'NetMQ.TerminatingException' in NetMQ.dll
Exception thrown: 'NetMQ.TerminatingException' in NetMQ.dll"


`CheckContextTerminated - yes, is terminated.
   at NetMQ.Core.SocketBase.CheckContextTerminated() in C:\Users\Developer\source\repos\netmq-4.0.0.1\src\NetMQ\Core\SocketBase.cs:line 146
   at NetMQ.Core.SocketBase.TryRecv(Msg& msg, TimeSpan timeout) in C:\Users\Developer\source\repos\netmq-4.0.0.1\src\NetMQ\Core\SocketBase.cs:line 889
   at NetMQ.NetMQSocket.TryReceive(Msg& msg, TimeSpan timeout) in C:\Users\Developer\source\repos\netmq-4.0.0.1\src\NetMQ\NetMQSocket.cs:line 358
   at NetMQ.ReceivingSocketExtensions.Receive(IReceivingSocket socket, Msg& msg) in C:\Users\Developer\source\repos\netmq-4.0.0.1\src\NetMQ\ReceivingSocketExtensions.cs:line 30
   at NetMQ.ReceivingSocketExtensions.SkipFrame(IReceivingSocket socket) in C:\Users\Developer\source\repos\netmq-4.0.0.1\src\NetMQ\ReceivingSocketExtensions.cs:line 840
   at NetMQ.Core.Utils.StopSignaler.<.ctor>b__2_0(Object <p0>, NetMQSocketEventArgs <p1>) in C:\Users\Developer\source\repos\netmq-4.0.0.1\src\NetMQ\Core\Utils\StopSignaler.cs:line 16
   at NetMQ.NetMQSocket.InvokeEvents(Object sender, PollEvents events) in C:\Users\Developer\source\repos\netmq-4.0.0.1\src\NetMQ\NetMQSocket.cs:line 340
   at NetMQ.NetMQPoller.Run() in C:\Users\Developer\source\repos\netmq-4.0.0.1\src\NetMQ\NetMQPoller.cs:line 395`

**Comment by tnavda** [comment]
They problem is if this is having on a "server context", and you want to hot restart the server, this leaves all kinds of issues of resources being left open.
