### ISSUE TITLE
MacOS: Subscriber Socket crashes if no Publisher available

### ISSUE THREAD

**Issue by justinrcs** [zeromq/netmq#756]
### Environment

    NetMQ Version:    4.0.0.1
    Operating System: MacOS Sierra 10.12.6
    .NET Version:  2.1.302 (.NET core)   

### Expected behaviour
Spinning up a subscriber (connect) without a publisher available (bind) shouldn't crash the subscriber application, it should just continue to wait until a connection can be made.

### Actual behaviour
Spinning up a subscriber when a publisher is not available, the subscriber socket will try connect, get several ConnectionRefused messages and then crash.
This happens if the subscriber is started before the publisher or if the subscriber was connected to a publisher and the publisher is subsequently shutdown or becomes unreachable (due to network partition).

**This seems to be a MacOS issue only, on Windows and Linux the subscriber survives publisher crashes or unavailability events.**

### Steps to reproduce the behaviour

Client.cs code:

```
using (var subSocket = new SubscriberSocket())
{
  subSocket.Options.ReceiveHighWatermark = 1000;
  subSocket.Connect("tcp://localhost:5563");
  subSocket.Subscribe("");
  Console.WriteLine("Subscriber socket connecting...");
  while (true)
  {
    string messageTopicReceived = subSocket.ReceiveFrameString();
    string messageReceived = subSocket.ReceiveFrameString();
    Console.WriteLine(messageReceived);
  }
}
```

1. Start Client.cs
2. Wait for ~20-30 seconds
3. App crashes:

`
Unhandled Exception: System.Net.Sockets.SocketException: Invalid argument
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue, Boolean silent)
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at NetMQ.Core.Transports.Tcp.TcpConnector.OutCompleted(SocketError socketError, Int32 bytesTransferred) in /Users/<>/Downloads/netmq-master/src/NetMQ/Core/Transports/Tcp/TcpConnector.cs:line 249
   at NetMQ.Core.IOObject.OutCompleted(SocketError socketError, Int32 bytesTransferred) in /Users/justinschwartz/Downloads/netmq-master/src/NetMQ/Core/IOObject.cs:line 118
   at NetMQ.Core.Utils.Proactor.Loop() in /Users/<>/Downloads/netmq-master/src/NetMQ/Core/Utils/Proactor.cs:line 133
   at System.Threading.Thread.ThreadMain_ThreadStart()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
`

**Comment by anilmujagic** [comment]
Current workaround that I use is building the `NetMQ` locally on macOS and referencing `NetMQ.dll` directly in the project.

**Comment by aventurella** [comment]
@anilmujagic which version do you build locally?

**Comment by anilmujagic** [comment]
Sorry for late response. I've built at commit 6b056d5a8cbfa5a99fd6f507abfaf104744b7ff8

> @anilmujagic which version do you build locally, I'm seeing the same issue on MacOS NET Core 2.1.403 and can confirm the OP's statement that:

**Comment by rfrancisco** [comment]
Any plans for a fix?
