### ISSUE TITLE
Can't Have more then 1024 worker connected to broker in majordomo implementation

### ISSUE THREAD

**Issue by KamranShahid** [zeromq/netmq#821]
### Environment

    NetMQ Version:    4.0.0.207
    Operating System: 
    .NET Version:     .net core 2.1

### Expected behaviour

Connected as many worker with broker. 

### Actual behaviour

At max 1024 worker get connected

### Steps to reproduce the behaviour

Have even tried  
//if (_lstWorkerHandlers.Count > 1024)
//{
//    BufferPool.SetBufferManagerBufferPool(1024 * 1024 * 10, 1024 * 2);
//}

**Comment by KamranShahid** [comment]
Getting error 
NetMQ.NetMQException: Exception of type 'NetMQ.NetMQException' was thrown.
   at NetMQ.Core.Ctx.CreateSocket(ZmqSocketType type)
   at NetMQ.NetMQSocket..ctor(ZmqSocketType socketType, String connectionString, DefaultAction defaultAction)
   at NetMQLib.MajordomoProtocol.MDPWorker.Connect()
   at NetMQLib.MajordomoProtocol.MDPWorker.Receive(NetMQMessage reply)
   at WorkerImplementation.StartWorker()
NetMQ.NetMQException: Exception of type 'NetMQ.NetMQException' was thrown.
   at NetMQ.Core.Ctx.CreateSocket(ZmqSocketType type)
   at NetMQ.NetMQSocket..ctor(ZmqSocketType socketType, String connectionString, DefaultAction defaultAction)
   at NetMQLib.MajordomoProtocol.MDPWorker.Connect()
   at NetMQLib.MajordomoProtocol.MDPWorker.Receive(NetMQMessage reply)
