### ISSUE TITLE
NET Core 3.1 Not supported?

### ISSUE THREAD

**Issue by Svisstack** [zeromq/netmq#846]
### Environment

    NetMQ Version:    4.0.0.273
    Operating System: Debian 10 @ Docker (mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim)
    .NET Version:     NET Core 3.1

### Expected behaviour

Works with NET Core 3.1

### Actual behaviour

Crashes immediately

```
[14:08:21 FTL] Unhandled exception
System.PlatformNotSupportedException: Socket.IOControl handles Windows-specific control codes and is not supported on this platform.
   at System.Net.Sockets.SocketPal.WindowsIoctl(SafeSocketHandle handle, Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue, Int32& optionLength)
   at System.Net.Sockets.Socket.IOControl(Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at System.Net.Sockets.Socket.IOControl(IOControlCode ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at AsyncIO.DotNet.NativeSocket.IOControl(IOControlCode ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at NetMQ.Core.Transports.Tcp.TcpConnector.OutCompleted(SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.IOObject.OutCompleted(SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart()
```

### Steps to reproduce the behaviour

Just run the app

**Comment by Svisstack** [comment]
Related https://github.com/somdoron/AsyncIO/issues/36

**Comment by somdoron** [comment]
I guess you tried to enable the tcp keepalive? that is only supported on windows.
You can use ZMTP3 hearbeat mechanism instead, although it is not on nuget yet, so you will have to compile from from master (all peers must support zmtp3 for heartbeat to work).

**Comment by somdoron** [comment]
https://github.com/zeromq/netmq/blob/master/src/NetMQ/SocketOptions.cs#L415

**Comment by Svisstack** [comment]
@somdoron Appreciate the fast response on this one as this blocked me hard. I confirm that without KeepAlive works correctly.
