### ISSUE TITLE
Name or service not known, when connecting using IP + Port.

### ISSUE THREAD

**Issue by Svisstack** [zeromq/netmq#928]
### Environment

    NetMQ Version:    4.0.1.4
    Operating System:  docker buster-slim
    .NET Version:     3.1 core

### Expected behaviour

ZeroMQ establishes connections.

### Actual behaviour

```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000005, 0xFFFDFFFF): Name or service not known
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at NetMQ.Core.Transports.Tcp.TcpAddress.Resolve(String name, Boolean ip4Only)
   at NetMQ.Core.SocketBase.Connect(String addr)
   at BBXT.Common.MQ.ZeroMQ.MQProducer.ReceiveStart(String address) in /src/BBXT.Common.MQ/ZeroMQ/MQProducer.cs:line 134
   at BBXT.Common.MQ.ZeroMQ.MQProducer.ReceiveThread() in /src/BBXT.Common.MQ/ZeroMQ/MQProducer.cs:line 104
```

OR

```
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (00000001, 11): Resource temporarily unavailable
   at System.Net.Dns.InternalGetHostByName(String hostName)
   at System.Net.Dns.GetHostEntry(String hostNameOrAddress)
   at NetMQ.Core.Transports.Tcp.TcpAddress.Resolve(String name, Boolean ip4Only)
   at NetMQ.Core.SocketBase.Connect(String addr)
   at BBXT.Common.MQ.ZeroMQ.MQProducer.ReceiveStart(String address) in /src/BBXT.Common.MQ/ZeroMQ/MQProducer.cs:line 134
   at BBXT.Common.MQ.ZeroMQ.MQProducer.ReceiveThread() in /src/BBXT.Common.MQ/ZeroMQ/MQProducer.cs:line 104
```

### Steps to reproduce the behaviour

`sub.Connect("tcp://1.2.3.4:12345");`

**Comment by Svisstack** [comment]
There is no name resolution here? How to prevent resolving this IP?

**Comment by somdoron** [comment]
NetMQ is only trying to resolve if the IP address is not valid. 

This method is used: https://docs.microsoft.com/en-us/dotnet/api/system.net.ipaddress.tryparse?view=netcore-3.1

So as long as you provide a parseable IP address it should work.

**Comment by Svisstack** [comment]
@somdoron Thanks for the information. I will extend logging to make sure if this happens again, I will able to make repro.

**Comment by Svisstack** [comment]
There was a local hostname provided. My fault.
