### ISSUE TITLE
NullReferenceException from NetMQ.Core.Pipe.ProcessPipeTermAck() Causes Crash

### ISSUE THREAD

**Issue by cdaylin** [zeromq/netmq#942]
### Environment

    NetMQ Version:    4.0.1.6
    Operating System:   Win 10 Pro
    .NET Version:    4.8.04084

### Expected behaviour

Our application does not crash due to an exception thrown from the NetMQ library.

### Actual behaviour

Our application is crashing intermittently due to an exception thrown from a NetMQ class.

The following Windows event log entry shows the stack trace:

> ((WINDOWS EventLog ERROR)) Time of Event: 9/29/2020 2:18:30 PM Application: [application name elided]
> CoreCLR Version: 4.6.27902.3
> Description: The process was terminated due to an unhandled exception.
> Exception Info: System.NullReferenceException: Object reference not set to an instance of an object.
>    at NetMQ.Core.Pipe.ProcessPipeTermAck()
>    at NetMQ.Core.ZObject.ProcessCommand(Command cmd)
>    at NetMQ.Core.IOThread.Ready()
>    at NetMQ.Core.Utils.Proactor.Loop()
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

### Steps to reproduce the behaviour

Unfortunately, I have not yet been able to reproduce this behavior outside of our application.  I am currently working on isolating the cause of this behavior in order to reproduce in a simple program that I can share.

I am hoping that someone might have some knowledge of this issue that will help me to identify the root cause more quickly.

Are there any known scenarios that can give rise to this type of exception?  For example, are there two operations that can cause a race condition leading to a null reference when executed concurrently on distinct threads?

**Comment by cdaylin** [comment]
Rather than attempting to identify and fix the defect causing this exception, I implemented an alternative means of inter-process communication that does not suffer from this problem.
