### ISSUE TITLE
socket.SendFrame(bytes) randomly throws "Offset and length were out of bounds"

### ISSUE THREAD

**Issue by bradmarder** [zeromq/netmq#951]
### Environment

    NetMQ Version: 4.0.1.6   
    Operating System: ubuntu 18.04
    .NET Version:   5

### 

Using a publisher socket in a tight loop, sending random packets will occasionally trigger this exception.
It's either using the SendFrames(byte[], int) overload or just the (byte[]), I'm not sure which causes it.

```
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
   at System.Buffer.BlockCopy(Array src, Int32 srcOffset, Array dst, Int32 dstOffset, Int32 count)
   at NetMQ.Core.Transports.EncoderBase.Encode(ByteArraySegment& data, Int32 size)
   at NetMQ.Core.Transports.StreamEngine.BeginSending()
   at NetMQ.Core.Transports.StreamEngine.FeedAction(Action action, SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.ZObject.ProcessCommand(Command cmd)
   at NetMQ.Core.IOThread.Ready()
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by bradmarder** [comment]
Closing this issue because I realized netmqsockets are not threadsafe.
