### ISSUE TITLE
Exception in AddProperty method 

### ISSUE THREAD

**Issue by MohNbat** [zeromq/netmq#955]
Hello,
When using Router Dealer Pattern, I'm getting sometimes this exception in client side :

Application: ###.exe Framework Version: v4.0.30319 

Description: The process was terminated due to an unhandled exception. Exception 

Info: System.Exception at NetMQ.Core.Mechanisms.Mechanism.AddProperty(System.Span1&lt;Byte&gt;, System.String, Byte[]) at NetMQ.Core.Mechanisms.Mechanism.AddBasicProperties(System.Span1<Byte>) at NetMQ.Core.Mechanisms.Mechanism.MakeCommandWithBasicProperties(NetMQ.Msg ByRef, System.String) at NetMQ.Core.Mechanisms.NullMechanism.NextHandshakeCommand(NetMQ.Msg ByRef) at NetMQ.Core.Transports.StreamEngine.NextHandshakeCommand(NetMQ.Msg ByRef) at NetMQ.Core.Transports.StreamEngine.BeginSending() at NetMQ.Core.Transports.StreamEngine.Activate() at NetMQ.Core.Transports.StreamEngine.HandleHandshake(Action, System.Net.Sockets.SocketError, Int32) at NetMQ.Core.Transports.StreamEngine.FeedAction(Action, System.Net.Sockets.SocketError, Int32) at NetMQ.Core.Utils.Proactor.Loop() at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at System.Threading.ThreadHelper.ThreadStart()

When decompiling the code it throws here: 

class = NetMQ.Core.Mechanisms.Mechanism
method = AddProperty(Span<byte> output, string name, byte[] value)
code = 
**_if (totalLength > output.Length) 
throw new Exception("totalLength of property exceed maximum size");_**

Could you help me about this error and tell me what's the reason of this?

### Environment

    NetMQ Version: 4.0.1.6
    Operating System: Windows 10 Enterprise and Windows Server 2016 Standard 64 bit
    .NET Version:  4.6.1

**Comment by djung31** [comment]
Hi, we are also seeing this error in .NET Core
```
System.Exception: totalLength of property exceed maximum size
   at NetMQ.Core.Mechanisms.Mechanism.AddProperty(Span`1 output, String name, Byte[] value)
   at NetMQ.Core.Mechanisms.Mechanism.AddBasicProperties(Span`1 output)
   at NetMQ.Core.Mechanisms.Mechanism.MakeCommandWithBasicProperties(Msg& msg, String prefix)
   at NetMQ.Core.Mechanisms.NullMechanism.NextHandshakeCommand(Msg& msg)
   at NetMQ.Core.Transports.StreamEngine.NextHandshakeCommand(Msg& msg)
   at NetMQ.Core.Transports.StreamEngine.BeginSending()
   at NetMQ.Core.Transports.StreamEngine.Activate()
   at NetMQ.Core.Transports.StreamEngine.HandleHandshake(Action action, SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.Transports.StreamEngine.Handle(Action action, SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.Transports.StreamEngine.FeedAction(Action action, SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.Transports.StreamEngine.InCompleted(SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.IOObject.InCompleted(SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.Utils.Proactor.Loop()
  ```

**Comment by taniaengel** [comment]
We have also seen this in NetMQ 4.0.1.6 on a Windows 10 Enterprise LTSC. Our app targets .NET 6.0.

System.Exception: totalLength of property exceed maximum size
   at NetMQ.Core.Mechanisms.Mechanism.AddProperty(Span`1 output, String name, Byte[] value)
   at NetMQ.Core.Mechanisms.Mechanism.AddBasicProperties(Span`1 output)
   at NetMQ.Core.Mechanisms.NullMechanism.NextHandshakeCommand(Msg& msg)
   at NetMQ.Core.Transports.StreamEngine.NextHandshakeCommand(Msg& msg)
   at NetMQ.Core.Transports.StreamEngine.BeginSending()
   at NetMQ.Core.Transports.StreamEngine.Activate()
   at NetMQ.Core.Transports.StreamEngine.HandleHandshake(Action action, SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.Transports.StreamEngine.FeedAction(Action action, SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.Thread.StartCallback()

**Comment by taniaengel** [comment]
I think it is useful to note that our DLL that references NetMQ has been using 4.0.1.6 for a long time. However, it used to target .NET 4.7.2 and we recently changed it to .NET Standard 2.0. The code using the socket is heavily tested and used by many of our services.

**Comment by dxdjgl** [comment]
Looking at the stacktrace, it seems like your code is changing the ZmqSocketOption.Identity option in a thread while processing is ongoing. Which causes the buffer inside Msg to be too small. I you look at the code inside Mechanism, the size is calculated using the BasicPropertiesLength, which is taking the size of the Identity into consideration, however since I expect your code to change Identity while processing the commandsize would be too small once the property should be added for real. Please note the sockets are not thread safe.
protected void MakeCommandWithBasicProperties(ref Msg msg, string prefix)
        {
            int commandSize = 1 + prefix.Length + BasicPropertiesLength;
            msg.InitPool(commandSize);
            msg.Put((byte)prefix.Length, 0);
            msg.Put(Encoding.ASCII, prefix, 1);
            
            AddBasicProperties(msg.Slice(prefix.Length + 1));
        }
