### ISSUE TITLE
NETMQ fails on Linux: Windows-specific control codes and is not supported on this platform.

### ISSUE THREAD

**Issue by maxima120** [zeromq/netmq#958]
### Environment

    NetMQ Version:    
    Operating System: CentOS8
    .NET Version:  5.0.1

### Expected behaviour
should work as promised on .NET Core platform

### Actual behaviour
Fails

### Steps to reproduce the behaviour
try to connect to a NETMQ server from ASP.NET Core app

```
Unhandled exception. System.PlatformNotSupportedException: Socket.IOControl handles Windows-specific control codes and is not supported on this platform.
   at System.Net.Sockets.SocketPal.WindowsIoctl(SafeSocketHandle handle, Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue, Int32& optionLength)
   at System.Net.Sockets.Socket.IOControl(Int32 ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at System.Net.Sockets.Socket.IOControl(IOControlCode ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at AsyncIO.DotNet.NativeSocket.IOControl(IOControlCode ioControlCode, Byte[] optionInValue, Byte[] optionOutValue)
   at NetMQ.Core.Transports.Tcp.TcpConnector.OutCompleted(SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.IOObject.OutCompleted(SocketError socketError, Int32 bytesTransferred)
   at NetMQ.Core.Utils.Proactor.Loop()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**Comment by daconglee** [comment]
up

**Comment by wjrogers** [comment]
FYI, support for TCP keep-alive was added to `SetSocketOption()` in .NET Core 3.0. Unfortunately, the new option names were never added to .NET Standard, so supporting TCP keep-alive on Linux would require adding a `netcoreapp3.1` (or newer) target to NetMQ. Then, code similar to this could be introduced to [TcpConnector](https://github.com/zeromq/netmq/blob/4a80a4a89d10617d7944057dc214bb8dd3360390/src/NetMQ/Core/Transports/Tcp/TcpConnector.cs#L251-L263) and [TcpListener](https://github.com/zeromq/netmq/blob/4a80a4a89d10617d7944057dc214bb8dd3360390/src/NetMQ/Core/Transports/Tcp/TcpListener.cs#L207-L218):

```csharp
#if NETCOREAPP3_1
// for .NET (Core) with the new socket options, use them (N.B. SetSocketOption units are seconds, not milliseconds)
if (m_options.TcpKeepaliveIdle != -1)
    m_s.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.TcpKeepAliveTime, m_options.TcpKeepaliveIdle / 1000);
if (m_options.TcpKeepaliveIntvl != -1)
    m_s.SetSocketOption(SocketOptionLevel.Tcp, SocketOptionName.TcpKeepAliveInterval, m_options.TcpKeepaliveIntvl / 1000);
#else
// ... retain existing code path for Windows / .NET Framework
#endif
```

**Comment by dnovhorodov** [comment]
Any news on the issue? When a fix could be expected? 
Running 4.0.1.6 version of NetMQ with netcoreapp3.1 is failing

**Comment by danielsilva-iq** [comment]
up!

**Comment by SpiritDogstar** [comment]
bump

**Comment by chrbauer** [comment]
I added [wjrogers](https://github.com/wjrogers) suggestion to a branch. For simplicity only .net8 is now supported:

https://github.com/chrbauer/netmq/tree/net8/tcp-keepalive-linux

It compiles, all tests are green. All nugets are up to date.

**Comment by chrbauer** [comment]
What do we need to do for an acceptable pull request?
1. There is a dedicided branch only for .net8 version. (This is currently the solution in the patch from the previous comment). 
2. We replace netstandard2.1 by netcoreapp3.1 and set TCP KeepAlive with #if NETCOREAPP_3_1
3. Like 2, but we keep the netstandard2.1 target

**Comment by chrbauer** [comment]
Hm. netcoreapp3.1 is not working, but net8.0.
==> https://github.com/zeromq/netmq/pull/1120

**Comment by chrbauer** [comment]
Should be solved with the release 4.0.2.1 (For net8.0 or greater)
I don't have permission to close this issue.
