### ISSUE TITLE
"Cannot close an uninitialised Msg" exception in NetMQ.Msg.Close()

### ISSUE THREAD

**Issue by elmerjfudd** [zeromq/netmq#975]
### Environment

NetMQ Version:  d297a27
Operating System: Windows 10
.NET Version: net47

### Expected behaviour

```NetMQ.Tests.NetMQQueueTests.EnqueueShouldNotBlockWhenCapacityIsZero``` passes without triggering any assert operations.

### Actual behaviour

We observe the following exception when running ```NetMQ.Tests.NetMQQueueTests.EnqueueShouldNotBlockWhenCapacityIsZero```:
```
Failed NetMQ.Tests.NetMQQueueTests.EnqueueShouldNotBlockWhenCapacityIsZero [1 s]
Error Message:
 NetMQ.FaultException : Cannot close an uninitialised Msg.
Stack Trace:
   at NetMQ.Msg.Close() in ../src/NetMQ/Msg.cs:line 441
 at NetMQ.NetMQQueue`1.Dispose() in ../src/NetMQ/NetMQQueue.cs:line 160
 at NetMQ.Tests.NetMQQueueTests.EnqueueShouldNotBlockWhenCapacityIsZero() in E:\GitBench\BugRepos\netmq\src\NetMQ.Tests\NetMQQueueTests.cs:line 51
```
Poking around, looks like a race between ```NetMQ.NetMQQueue.Dispose()``` and ```NetMQ.NetMQQueue.Dequeue()```. Most likely, ```NetMQ.Msg.Close()``` is called twice on ```m_dequeueMsg```.

### Steps to reproduce the behaviour

Originally, the bug was happeneing spuriously, but we can enhance the issue by slightly modifying the original test in ```NetMQQueueTests.cs``` (changes marked as comments below):

```
[Fact]
public void EnqueueShouldNotBlockWhenCapacityIsZero2()
{
    using (var mockSocket = new PairSocket())
    using (var queue = new NetMQQueue<int>())
    {
        int socketWatermarkCapacity = mockSocket.Options.SendHighWatermark + mockSocket.Options.ReceiveHighWatermark;

        Task task1 = Task.Run(() =>
        {
            for (int i = 0; i < socketWatermarkCapacity + 100; i++)
            {
                queue.Enqueue(i);
            }
        });

        Task task2 = Task.Run(() =>  // <--- running a set of Dequeue() ops concurrently with Enqueue() ops and the Dispose() at the end of the "using" block
        {
            for (int i = 0; i < socketWatermarkCapacity + 100; i++)
            {
                queue.Dequeue();
            }
        });

        bool completed = task2.Wait(TimeSpan.FromSeconds(1));
    }
}
```

**Comment by bastoica** [comment]
Looks like this data race has similar side effects as #952. Maybe the root causes are related?

**Comment by elmerjfudd** [comment]
Looks like this data race has similar side effects as #952. Maybe the root causes are related?

**Comment by elmerjfudd** [comment]
Looks like this data race has similar side effects as #930. Maybe the root causes are related?

**Comment by elmerjfudd** [comment]
This issue still occurs with the most recent commit, i.e., d934760
I was wondering if there is any fix currently in the works.

**Comment by follesoe** [comment]
Facing the same issue on Xamarin.iOS, and Xamasrin.Android.

**Comment by elmerjfudd** [comment]
Just checking in, because it looks like this is still happening in the latest stable version.

**Comment by vbergara** [comment]
I'm still facing this issue in the latest version.

**Comment by getarobo** [comment]
Please!!!! need help on this!!!!! ANY IDEAS?

**Comment by guipalazzo** [comment]
I'm still facing this issue in the latest version.

**Comment by follesoe** [comment]
Same...

**Comment by getarobo** [comment]
I have been using pub and sub in a same thread <-- this caused "Cannot close an uninitialised Msg" sometimes.

Now I run subscriber and publisher on different thread. I have no longer seen such error. 

something like this (ran on unity)
```
// sockets
        public PublisherSocket _pubSocket;
        public SubscriberSocket _subSocket;

        private readonly ConcurrentQueue<ZmqMsg> _msgRecvQueue = new ConcurrentQueue<ZmqMsg>();
        private BlockingCollection<NetMQMessage> _toSendQueue = new BlockingCollection<NetMQMessage>()

        private Thread _subThread;
        private Thread _pubThread;
...

// start
            AsyncIO.ForceDotNet.Force();
            NetMQConfig.Linger = new TimeSpan(0, 0, 0);

            _pubThread = new Thread(_PubWorkerThread);
            _pubThread.Start();

            _subThread = new Thread(_SubWorkerThread);
            _subThread.Start();
```

**Comment by LiorBanai** [comment]
Still exists in latest version

**Comment by aalfath** [comment]
I can confirm that this still exists in the latest version.

**Comment by WojakGra** [comment]
I found my code that is working but using queue as windows service

## Server
### Class
```C#
using System;
using System.Collections.Concurrent;
using System.Threading;
using System.Threading.Tasks;
using NetMQ.Sockets;
using NetMQ;
using System.IO;

namespace ...
{
    public class MessageQueueService
    {
        private readonly ConcurrentQueue<String> _messageQueue;
        private readonly SemaphoreSlim _signal;
        private readonly CancellationTokenSource _cts;

        private static readonly Object lockObj = new Object();

        public Boolean IsConnected { get; private set; }

        private PublisherSocket mqserver;

        public MessageQueueService()
        {
            IsConnected = false;
            _messageQueue = new ConcurrentQueue<String>();
            _signal = new SemaphoreSlim(0);
            _cts = new CancellationTokenSource();
        }

        public void NetMQ_Start()
        {
            mqserver = new PublisherSocket();
            mqserver.Bind("tcp://*:5555");
        }

        public void NetMQ_Stop()
        {
            StopProcessingQueue();
            mqserver.Close();
            mqserver.Dispose();
            NetMQConfig.Cleanup();
        }

        public void EnqueueMessage(String message)
        {
            _messageQueue.Enqueue(message);
            _signal.Release();
        }

        public async Task StartProcessingQueue()
        {
            IsConnected = true;
            while (!_cts.Token.IsCancellationRequested)
            {
                await _signal.WaitAsync(_cts.Token);

                if (_messageQueue.TryDequeue(out String message))
                {
                    try
                    {
                        mqserver.SendFrame(message);
                    }
                    catch (NetMQ.FaultException e)
                    {
                        LogEvent($"NetMQ SendFrame Fault Error | {e.Message}");
                    }
                    catch (Exception e)
                    {
                        LogEvent($"NetMQ SendFrame Error | {e.Message}");
                    }
                }
            }
        }

        public void StopProcessingQueue()
        {
            _cts.Cancel();
        }

        private void LogEvent(String message)
        {
            lock (lockObj)
            {
                try
                {
                    System.IO.Directory.CreateDirectory(@"C:\X");
                    using (StreamWriter writer = new StreamWriter(@"C:\X\" + DateTime.Now.ToString("yyyyMMdd") + "_netmqlogs.txt", true))
                    {
                        writer.WriteLine(DateTime.Now.ToString("HH:mm:ss.fff") + " | " + message);
                    }
                }
                catch (Exception)
                {
                }
            }
        }
    }
}
```

### Using class in service
```C#
MessageQueueService messageQueueService = new MessageQueueService();

public MainService()
{
	// ...
}

protected override void OnStart(String[] args)
{
	messageQueueService.NetMQ_Start();
	Task.Run(() => messageQueueService.StartProcessingQueue());
	while (true)
	{
		if (messageQueueService.IsConnected)
		{
			// ...
		}
	}
}

protected override void OnStop()
{
	LogEvent("Service stopped.");
	messageQueueService.NetMQ_Stop();

	Environment.Exit(0);
}
```


## Client
```C#
private void InitializeNetMQ()
{
	mqclient = new SubscriberSocket();
	mqclient.Connect("tcp://127.0.0.1:5555");
	mqclient.Subscribe("");
	mqclient.ReceiveReady += Subscriber_ReceiveReady;

	poller = new NetMQPoller { mqclient };
	poller.RunAsync();
}

private void Subscriber_ReceiveReady(object sender, NetMQSocketEventArgs e)
{
	String message = e.Socket.ReceiveFrameString();
	if (message != null || message != "")
	{
		// ...
	}
}
```
